### ISSUE TITLE
hashMap

### ISSUE THREAD

**Issue by MazeChaZer** [lstrojny/functional-php#100]
For my own use I wrote a function called `hashMap` to create associative arrays:

```
>>> hashMap(
...     ['abc', 'foobar'],
...     function ($value) {
...         return [$value[0], $value];
...     }
... )
=> [
     "a" => "abc",
     "f" => "foobar",
   ]
```

```php
function hashMap($collection, callable $callback)
{
    InvalidArgumentException::assertCollection($collection, __FUNCTION__, 1);
    
    $aggregation = [];

    foreach ($collection as $index => $element) {
        list($key, $value) = $callback($element, $index, $collection);
        $aggregation[$key] = $value;
    }

    return $aggregation;
}
```

Is this something that would also be useful to others? If yes, I can prepare a proper pull request. Of course it can be named differently if there is a better term for what this function does.

**Comment by lstrojny** [comment]
Looks useful! @ajb-in do you have a good idea for a name?

**Comment by ajb-in** [comment]
No good ideas, other than I'd refer to "keys" rather than "hashes" (and would probably reflect that in the name of the argument).
Also, note that this is equivalent to `array_combine(map($collection, $callback), $collection)`

**Comment by MazeChaZer** [comment]
Thanks for the feedback! @ajb-in The function is not exactly equivalent to your example because apart from the keys the values can also be mapped in the callback.

```
>>> hashMap(
...     ['abc', 'foobar'],
...     function ($value) {
...         return [$value[0], strtoupper($value)];
...     }
... )
=> [
     "a" => "ABC",
     "f" => "FOOBAR",
   ]
```

Your example describes another use case: Mapping only the keys. This would have been sufficient for my needs, even better; perhaps this is also a useful function? A better name for `hashMap` could be `keyValueMap` and your example could be called `keyMap`.

In comparison:

```
>>> map(
...     ['abc', 'foobar'],
...     function ($value) {
...         return strtoupper($value);
...     }
... )
=> [
     "ABC",
     "FOOBAR",
   ]
>>> keyMap(
...     ['abc', 'foobar'],
...     function ($value) {
...         return $value[0];
...     }
... )
=> [
     "a" => "abc",
     "f" => "foobar",
   ]
>>> keyValueMap(
...     ['abc', 'foobar'],
...     function ($value) {
...         return [$value[0], strtoupper($value)];
...     }
... )
=> [
     "a" => "ABC",
     "f" => "FOOBAR",
   ]
```

What do you think?

**Comment by lstrojny** [comment]
What about {{mapHash()}}?

**Comment by MazeChaZer** [comment]
@lstrojny Sounds good to me. I like that even better than the `keyValueMap` approach.

**Comment by MazeChaZer** [comment]
Are we at a consens here? Should I start implementing/testing/documenting the `mapKeys()` function?

**Comment by ajb-in** [comment]
I for one would use `mapKeys` for a different idea (something akin to [Haskell's `mapKeys`](https://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Map-Strict.html#v:mapKeys)).
But then again, I don't have a better name for this one, and can't find a precedent on the literature apart from [the Schwartzian transform](https://en.wikipedia.org/wiki/Schwartzian_transform).

**Comment by MazeChaZer** [comment]
What about `reindex()`?

**Comment by lstrojny** [comment]
Sounds good to me

**Comment by MazeChaZer** [comment]
Ok, I'm starting to work on this, if we find an even better name we can still change it later on.

**Comment by MazeChaZer** [comment]
Mh, what is supposed to happen if the callback produces  duplicate keys? Should an exception be thrown  or should later values just overwrite previous values that had the same key? I tend to throw an exception.

**Comment by MazeChaZer** [comment]
I looked a little further into this. The PHP builtins `array_flip()` and `array_combine()` overwrite previous values which had the same key. Furthermore I saw that in this library exceptions are only thrown for invalid arguments. So I guess the first alternative, just overwriting previous values, makes more sense after all.

**Comment by ajb-in** [comment]
+1 on `reindex`.
Also agree with your dup key resolution.

**Comment by MazeChaZer** [comment]
Thanks for the discussion
