### ISSUE TITLE
[RFC] provide a `not` function

### ISSUE THREAD

**Issue by docteurklein** [lstrojny/functional-php#101]
Is it me or one currently can't invert a boolean-returning function ?

I'd like a `not` function looking like:

``` php
namespace Functional;

function not(callable $callback) {
    return function($value) use ($callback) {
        return !$callback($value);
    };
}
```

see https://3v4l.org/G3vtd for a working impl.

Do you think it's a good idea?
If yes, I can try to make a PR.

Thanks!

**Comment by lstrojny** [comment]
I like it. But congratulations, you are traveling uncharted territory: operator functions. I can think of more: eq(), neq(), etc. So that one can write `filter($list, and(neq('foo'), neq('bar'))` and so on. Interested on working on the whole topic?

**Comment by docteurklein** [comment]
Interesting topic indeed :)

I can try to implement a few of them, but this could be an iterative work, right?
Do you have an idea of a separate namespace for that?

Small note, we need to alias `and` and `or` functions because they are reserved keywords.

**Comment by docteurklein** [comment]
@lstrojny another question regarding an implementation detail  of `neq`.
Let's say we have implemented `not` and `eq`. 

Should we implement `neq` by simply composing `neq = not('eq')` ? 
Or should we use directly the `!=` operator?

**Comment by lstrojny** [comment]
@docteurklein I always try to implement the most basic version of a function, rather not reusing existing functionality but full reimplementing them. Leads to uglier code but that’s OK for primitives.

**Comment by docteurklein** [comment]
agreed. I ended up using the native operator (much easier)

**Comment by MarcoWorms** [comment]
The native operator is handy but it's not a function. When refactoring some code into a function pipeline with `compose` it's much better to have a `not` function. Also you can achieve a declarative code style that doesn't need native operators when you have functions for everything :D

**Comment by leocavalcante** [comment]
This could be closed, I guess.
https://github.com/lstrojny/functional-php/blob/master/src/Functional/Not.php

**Comment by docteurklein** [comment]
right! thanks
