### ISSUE TITLE
zip: keys are taken from the first array

### ISSUE THREAD

**Issue by Erikvv** [lstrojny/functional-php#108]
I would expect it to look in all arrays like it does in lodash. And fill the missing indexes with null like it does now.

I can provide a fix if you want, or maybe we can define another function, maybe 'zipLongest'

**Comment by lstrojny** [comment]
Sounds indeed like a bug/oversight when implementing the original function. Happy to have a fix for it.

**Comment by krtek4** [comment]
Actually `zip` has various implementation regarding this in multiple languages.

- the `array_map` trick in PHP (passing `null` as the function) does what you ask
- Ruby : add `nil` values ( http://apidock.com/ruby/Array/zip )
- Python: elements are truncated ( https://docs.python.org/2/library/functions.html#zip )
- Haskell: elements are truncated ( http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:zip )
- Scala : elements are truncated ( http://www.scala-lang.org/api/2.10.6/#scala.collection.immutable.List )

So I would say it is more of a chose a side kind of thing :P

**Comment by lstrojny** [comment]
OK, I am convinced. I changed my mind. Let’s add a `zip_all()` function (or some other name).
