### ISSUE TITLE
[RFC] `pick` should be renamed `picker` to be consistent with `invoker`

### ISSUE THREAD

**Issue by docteurklein** [lstrojny/functional-php#110]
hey there :)

I'd like to have a function that returns the value of an array at a given index **for each element of a collection**. like `invoke` does currently for collections of objects).

I think `pick` should be renamed to `picker` (like `invoker` respectively)
and a new `pick` function would `map` `picker` to a collection.

Now I know renaming things is a big BC break so I wouldn't bother naming it differently.
Thoughts?

**Comment by docteurklein** [comment]
currently I have to do something like:
```php
$locales = f\map($data['translations'], f\partial_any('Functional\pick', f\…, 'locale'));
```

**Comment by lstrojny** [comment]
`pluck($data['translations'], 'locale')` should work, no?
