### ISSUE TITLE
[IHNFIWIWD] The compose function is executed left to right

### ISSUE THREAD

**Issue by cullylarson** [lstrojny/functional-php#117]
It's pretty unusual behavior for `compose` to execute left to right.  Every other `compose` implementation I've come across executes right to left.  One other issues is that this behavior isn't documented in `docs/functional-php.md`

**Comment by lstrojny** [comment]
Indeed, that was a mistake when implementing it but it’s probably too late to fix that now in a sane way. The only way I would see is adding a function with a different name to do the right thing.

**Comment by cullylarson** [comment]
Ah, yeah, that's a tough one.  A good solution might be to just be very explicit about that functionality in the documentation.  I only noticed it was happening after spending some time trying to debug a function that was using `compose`, and then looking at the code for `compose`.  I actually had to go back and change all of my other uses of `compose`.

**Comment by MarcoWorms** [comment]
Is it too harmful to break the current interface and make `compose` do right-to-left composition which would be the expected behaviour and add a `pipe` function that does the current left-to-right composition? Ramda (https://github.com/ramda/ramda) does it this way and it seems really sane.

**Comment by lstrojny** [comment]
@MarcoWorms I wouldn’t wanna do this for 1.x but I could very well imagine doing this for 2.x.

**Comment by lstrojny** [comment]
Will be addressed with 2.0
