### ISSUE TITLE
It would be nice if the library functions were all curried

### ISSUE THREAD

**Issue by cullylarson** [lstrojny/functional-php#118]
This would let you do things like:

```php
$trimAll = map(trim);

$trimAll([' a', 'b ', ' c ']); // results in:  ['a', 'b', 'c']
```

**Comment by cullylarson** [comment]
Since PHP doesn't always treat functions as first class objects, you obviously can't just wrap a namespaced function in curry.  But, with a little extra cruft, you can still accomplish it like this:

```
function add(...$args) {
  $add = curry(function($x, $y) {
    return $x + $y;
  });

  return call_user_func_array($add, $args);
}
```

**Comment by cullylarson** [comment]
Though, looking at the argument order of many of the functions in the library, they wouldn't necessarily lend themselves well to curried use.

**Comment by lstrojny** [comment]
I can’t think of a way to do that in a way that performs well, it’s rather an engine feature than something I would do with this library. So until somebody convinces me with a prototype, I don't want to work on this.
