### ISSUE TITLE
Bundled functions in single file for production

### ISSUE THREAD

**Issue by mh-ovos** [lstrojny/functional-php#119]
Hi,
I reckon that including ~70 files on every script execution might be a bit of a performance hit. Would you consider adding a bundled file with all functions inside as some kind of dist "build" and autoload just that file in composer.json definition?

**Comment by lstrojny** [comment]
@mh-ovos can you check wether that’s actually true as it shouldn't matter with opcache enabled.

**Comment by lstrojny** [comment]
Closing for now
