### ISSUE TITLE
Comparison operations API

### ISSUE THREAD

**Issue by leocavalcante** [lstrojny/functional-php#124]
About implementing comparison operations as functions, before I'd like to discuss the API first.
Operations: http://php.net/manual/en/language.operators.comparison.php

Suggestions are:

| PHP Doc Name | API | 
| --- | --- |
| Equal | `equal`, `equals`, `eq` |
| Identical | `identical`, `strict_eq`, `seq` |
| Not equal | `not_equal`, `not_equals`, `neq` |
| Not identical | `not_identical`, `not_strict_eq`, `nseq` |
| Less than | `less_than`, `lt` |
| Greater than | `greater_than`, `gt` |
| Less than or equal to | `less_than_or_eq`, `lte` |
| Greater than or equal to | `greater_than_or_eq`, `gte` |
| Spaceship | `spaceship`, `lteqgt` |

I personally prefer the abbreviations. e.g.:

```php
// using cond/always from #123

$message = cond([
    [lte(16), always('Can drive in USA')],
    [lte(18), always('Can drive and drink in Brazil')],
    [lte(21), always('Can drink in USA')],
    [gte(60), always('Getting old')],
]);

echo $message(18); // ~> Can drive and drink in Brazil
echo $message(60); // ~> Getting old
```

**Comment by lstrojny** [comment]
Here are my preferences:

| PHP Doc Name | API | 
| --- | --- |
| Equal | `equal` |
| Identical | `identical` |
| Not equal | `not_equal` |
| Not identical | `not_identical` |
| Less than | `less_than` |
| Greater than | `greater_than` |
| Less than or equal to | `less_than_or_equal` |
| Greater than or equal to | `greater_than_or_equal` |
| Spaceship | `lexicographic_compare ` |

**Comment by leocavalcante** [comment]
Ok, seems good, just crossed my mind that would be better to use full names and let abbreviations for `use` alias:
```php
use Functional\greater_than_or_equal as gte;
```
