### ISSUE TITLE
Implode/Join for lists

### ISSUE THREAD

**Issue by MazeChaZer** [lstrojny/functional-php#126]
I may be missing something here, but is there some kind of `join` function that behaves like `implode` but returns a list?

```php
join('-', ['a', 'b', 'c']) === ['a', '-', 'b', '-', 'c']
```

**Comment by lstrojny** [comment]
There isn’t one yet. Feel free to contribute one!

**Comment by MazeChaZer** [comment]
Great! I will look into it when I have the time.
