### ISSUE TITLE
Separate namespace for functions that are curried by default

### ISSUE THREAD

**Issue by BrainMaestro** [lstrojny/functional-php#136]
Like #118 suggested, it would be a good idea to curry functions by default. Since we don't want to alter the already existing functions, there could be a namespace `Functional\curried` where all the curried versions of the functions live. We could even use the flip function from #132 if it gets merged to flip the order to make them easier for curried use.

Thoughts?
/cc @lstrojny @cullylarson

**Comment by cullylarson** [comment]
That sounds like a good solution.  It would even let you deprecate the old functions.  One downside would be autoloading a whole extra set of files in `vendor/autoload.php`.  Other options would be: just keep things the way they are with this library and start a new library for curried functions, or join up with another project like [widmogrod/php-functional](https://github.com/widmogrod/php-functional).

**Comment by BrainMaestro** [comment]
Yeah on second thought, php might make this a little too complicated. Since we will be mostly unable to reuse the initially defined functions. Thanks for the response though, I'll look into the other suggestions.
