### ISSUE TITLE
Ellipsis constant is defined as a function?

### ISSUE THREAD

**Issue by Ocramius** [lstrojny/functional-php#138]
Unsure if this is a valid report yet, but PHP 7.2 (current `master` branch of PHP) [reports an error in my builds](https://travis-ci.org/Ocramius/ProxyManager/jobs/222789367#L370) due to [this line](https://github.com/lstrojny/functional-php/blob/f31a0beb08ad6c6fe0d7a7899efb7d868ae708eb/src/Functional/PartialAny.php#L87), copied for reference:

```php
/** Define unicode ellipsis constant */
define('Functional\\…', …());
```

Apparently, that defines a constant that is actually a function, and that raises a `WARNING` in PHP 7.2.

**Comment by lstrojny** [comment]
Hmmm, it looks like I can no longer register a resource as a constant 👎 
That was such a cute trick to mark a parameter as partial but it looks like I have to find something better

**Comment by lstrojny** [comment]
Attempt to fix this issue: 7633c9f235a8946bb9e36f994010e018806f8ce8

**Comment by Ocramius** [comment]
R U TROLEING THE ENGINE?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by lstrojny** [comment]
@Ocramius I try but without any luck. So `random_bytes()` it is.

See 5ed5ee0

**Comment by lstrojny** [comment]
Fixed in latest master. Thanks @Ocramius !

**Comment by Ocramius** [comment]
@lstrojny thanks!
