### ISSUE TITLE
[DOC] flip looses the arity of the function

### ISSUE THREAD

**Issue by semmel** [lstrojny/functional-php#140]
Thus automatic currying a flipped function is not possible. Instead one needs to specify the arity using `curry_n`.
I guess that behavior should be mentioned in the documentation.

I wonder if argument flipping is useful at all for `n ≠ 2`, because optional parameters on third and higher places will suddenly become compulsory. 
Especially when providing a curried, data-last version of *functional-php* for #118, I guess `curry_n(2, flip('Functional\xxx'))` covers nearly all cases.

**Comment by lstrojny** [comment]
Good point. I am not sure this is fixable in a way that will still perform well (e.g. without reflection). Give me a bit of time to think about it but at least mentioning it in the docs is something we should do.
