### ISSUE TITLE
Warning for PartialAny.php on line 87 (PHP Nightly)

### ISSUE THREAD

**Issue by redaxmedia** [lstrojny/functional-php#142]
Hello,

since I enabled warnings for PHPUnit, I got this: 

> PHPUnit\Framework\Exception: PHP Warning:  Constants may only evaluate to scalar values or arrays in /home/travis/build/redaxmedia/redaxscript/vendor/lstrojny/functional-php/src/Functional/PartialAny.php on line 87

PHP: 7.2.0-dev (cli) (built: May 27 2017 22:53:52) ( ZTS )
Link: https://travis-ci.org/redaxmedia/redaxscript/jobs/236892403

Best regards
Henry

**Comment by lstrojny** [comment]
Can you try master? This should be fixed in the latest version of functional

**Comment by redaxmedia** [comment]
Sorry but I don't use your dependency by myself.

I forced the `dev-master` and these are the results:
https://travis-ci.org/redaxmedia/redaxscript/builds/238712732

**Comment by lstrojny** [comment]
No worries, glad it is fixed.

**Comment by redaxmedia** [comment]
Please create a new release :-)
