### ISSUE TITLE
[FEATURE] Count Where

### ISSUE THREAD

**Issue by mgiraud** [lstrojny/functional-php#143]
Hi,

Is there any way to achieve a countWhere equivalent with the current methods ?

The countWhere method would take a collection and a callable;
If the callable returns true then a counter is incremented.

The countWhere method returns the counter.

Thx

**Comment by lstrojny** [comment]
@mgiraud Would {{count(filter(…, …))}} work?

**Comment by mgiraud** [comment]
Yes, it's just a little bit more expensive
