### ISSUE TITLE
Pluck error with __get()

### ISSUE THREAD

**Issue by Superpat** [lstrojny/functional-php#146]
Example:

``` php
use function Functional\pluck;

class Model {
   private $x;
   private $y;
   
   public function __construct($x, $y) {
       $this->x = $x;
       $this->y = $y;
   }
   
   public function __get($property) {
        if (property_exists($this, $property)) {
            return $this->$property;
         }
    }
}

$array = [new Model(2,3)];
var_dump(pluck($array, 'x'));
```
The output of this is: array(1) { [0]=> NULL }

**Comment by Superpat** [comment]
The main problem is ``isset($element->{$propertyName})`` returns false.

**Comment by jdreesen** [comment]
Why not just implement `Model::__isset()`?

**Comment by Superpat** [comment]
Yep, completely forgot about __isset, solves the problems, thanks!

**Comment by lstrojny** [comment]
To follow up on that: pluck() will not be perfect and there will always be certain kind of objects that behave weirdly with it. Nevertheless, I am glad your found a way to solve the issue.
