### ISSUE TITLE
More 'haskelly' definition of Flatten

### ISSUE THREAD

**Issue by ianchanning** [lstrojny/functional-php#151]
In [Flatten][1], the underlying code seems rather of an imperative nature.

As I understand, flattening a list in Haskell (from [Learn You a Haskell chapter on Monoids][2]), is simply mapping `concat` over the list. The equivalent in PHP would be this:

```php
array_reduce($x, 'array_merge', []);
```
That seems incredibly neat. Here's some basic testing I did in Psysh:

```php
>>> $flatten = function ($x) { return array_reduce($x, 'array_merge', []); };
>>> $flatten([[1], [1,2], [1,2,3]]);
=> [
     1,
     1,
     2,
     1,
     2,
     3,
   ]
```

The major problem with this is that it just does one level of flattening and doesn't match to your definition of 'flatten' which is more recursive. But I think it can be enhanced to handle your multidimensional collections whilst still having a somewhat more functional core. 

Apologies if I'm stating something glaringly obvious, I don't know all the cases you're handling or if this makes sense with the rest of your code.

  [1]: https://github.com/lstrojny/functional-php/blob/master/src/Functional/Flatten.php
  [2]: http://learnyouahaskell.com/functors-applicative-functors-and-monoids#monoids

**Comment by lstrojny** [comment]
Thanks for the observation @ianchanning. The implementation of quite some functions is not very functional but rather quite imperative. I don't want to change the definition of Functional PHP’s as it’s used in real world projects and B/C breaks are a thing. So we can either add another function or there might be one that fits your use case already. Did you check out flat_map() with an identity function?

**Comment by ianchanning** [comment]
Apologies, my intention wasn't to change the output of the function. It was mostly just because I was curious about it. My rather basic suggestion here would need definitely need extending so that it would give the exact same output as the current `Flatten`. But it would perhaps be nice to have a lower level method that just did the single flatten (with a separate name as you suggest) and then build on that to handle all the cases that the current `Flatten` does.

I hadn't looked at `flat_map` will give it a try.
