### ISSUE TITLE
if_else with more than 1 argument

### ISSUE THREAD

**Issue by poissob** [lstrojny/functional-php#167]
Hello,

I was wondering why the `if_else` function doesn't take more than one argument?
In my case, I'd like to be able to call a function with multiple arguments like so:
```
$return = if_else($condition, $ifTrue, $ifFalse);
return $return($param1, $param2);
```

Is there any particular reason for this not to work currently?

Regards,

**Comment by zanemmm** [comment]
yes, the `if_else` function just take one argument.

I think this function may help you
``` php
function if_else(callable $if, callable $then, callable $else)
{
    return function (...$value) use ($if, $then, $else) {
        return $if(...$value) ? $then(...$value) : $else(...$value);
    };
}
```

**Comment by lstrojny** [comment]
What we are missing is logical operator functions here: 

```php
$cond = if_else(…, …, …);
$cond(and($param1, $param2));
$cond(or($param1, $param2));
$cond(xor($param1, $param2));
```

Happy to get a pull request for those
