### ISSUE TITLE
The opposite of `select_keys`

### ISSUE THREAD

**Issue by jasonmm** [lstrojny/functional-php#203]
The [`select_keys` function](https://github.com/lstrojny/functional-php/blob/master/docs/functional-php.md#select_keys) is extremely handy. However, sometimes I only know which keys I don't want, or the number of keys I don't want is significantly smaller than those I do want. I did not see a function (for example, `remove_keys`) that would allow for that.

Is it expected that key removal be accomplished with other functions? Would you be interested in a PR for a `remove_keys` function?

**Comment by Erikvv** [comment]
Maybe `omit_keys` is a better name

**Comment by jasonmm** [comment]
I think `omit_keys` is a better name. Thank you! 

Your suggestion also inspired me to think of `ignore_keys`, or [`dissoc`](http://clojuredocs.org/clojure.core/dissoc) (since the [`select_keys`](https://github.com/lstrojny/functional-php/blob/master/docs/functional-php.md#select_keys) function was [inspired by Clojure](https://github.com/lstrojny/functional-php/pull/145)) as possible names.
