### ISSUE TITLE
pick should use array_key_exists instead of isset

### ISSUE THREAD

**Issue by lorenzomar** [lstrojny/functional-php#217]
pick source code use `isset` to check if the given key is present in the collection. This implies that  NULL values are not valid but they should be. What about to use array_key_exists?

**Comment by lstrojny** [comment]
The behavior difference would be in case you have a default value other than null specified, right?

**Comment by lorenzomar** [comment]
Hey lstrojny, so sorry for the delay. 
From a pragmatic point of view you're right but i think that the real difference is more conceptual. `isset` doesn't consider `null` as a valid value but there are cases where a collection contains a mix of null values, falsy value, etc and they are all right.
In that cases current implementation of `pick` fails.

**Comment by lstrojny** [comment]
Makes all sense, should indeed be `array_key_exists`. Want to open a PR for it?
