### ISSUE TITLE
Make these functions more expressive

### ISSUE THREAD

**Issue by videni** [lstrojny/functional-php#220]
current we have to do something like this.
```
map(
    filter($fields, function($field){
        return 'user' != $field->fieldTypeIdentifier;
    }), 
    function($field){
        return [
            $field->fieldDefIdentifier => $field->value
        ];
    }
)
```

A better approach.
```
filter($fields, function($field){
    return 'ezuser' != $field->fieldTypeIdentifier;
})->map(function($field){
    return [
        $field->fieldDefIdentifier => $field->value
    ];
})
```

**Comment by tzkmx** [comment]
This would require returning objects to chain methods, reminds me of Collection class of Illuminate (Laravel), as another consumer of this package, I don't get what enhancement that would give, but is clearly a lot of effort to implement.

**Comment by lstrojny** [comment]
I don’t plan to change the API towards a collection API in the future

**Comment by drupol** [comment]
@videni maybe this project would help you ? https://github.com/loophp/collection

Feel free to let me know if my comment is not welcome and I'll delete it straight.

Keep up the good work.
