### ISSUE TITLE
[BUG] 1.14.0 breaks when opcache.preload is enabled

### ISSUE THREAD

**Issue by danfraticiu** [lstrojny/functional-php#226]
Our system just crashed and burned in producation with this error after `composer update` install 1.14 

```
Fatal error: Cannot redeclare Functional\match() (previously declared in /srv/app/vendor/lstrojny/functional-php/src/Functional/Matching.php(46) : eval()’d code:3) in /srv/app/vendor/lstrojny/functional-php/src/Functional/Matching.php(46) : eval()’d code on line 3
```

We haven't looked much into it, but disabling opcache.preload fixed the issue. For now we will downgrade to 1.12.0.

Not sure what the reasoning for the `eval` block was, but I'm pretty sure it's not needed it as you could declare the function inside the `if`

ex: https://3v4l.org/Y8Ulb

LE: I can send a PR tomorrow if needed.

**Comment by lstrojny** [comment]
Fixed in 9e8363e3cb9db924327f51b5804f4dfba03605aa
