### ISSUE TITLE
Proposal: Add compact()

### ISSUE THREAD

**Issue by phanan** [lstrojny/functional-php#232]
WDYT about adding a `Functional\compact()` function that removes all falsy values from a collection [à la lodash](https://lodash.com/docs/4.17.15#compact)? It can be named something like `compress()` as well if there's any concern regarding the existing `compact()` in PHP. I can give it a try.

**Comment by lstrojny** [comment]
`select([0, false, 1])` should do that already, no?

**Comment by phanan** [comment]
Yeah, as so should `array_filter` and the likes, but I'd argue a dedicated function is better, even if its internal implementation is exactly the same.

**Comment by lstrojny** [comment]
That’s a too limited purpose in my mind that it would warrant an additional function. Let’s not add it! 😄
