### ISSUE TITLE
Introduce autocurring and function composition

### ISSUE THREAD

**Issue by psliwa** [lstrojny/functional-php#41]
What do you think about introducing to functional php autocurring and function composition?

I have created working prototype of library with autocurring, function composition and making`$collection` as last argument: https://github.com/psliwa/rfp

In my opinion it looks promising, allows to take advantage of functional programming in even better way. There is the chance to make new release, aka "functional php 2"?

**Comment by mpajunen** [comment]
Some very interesting thoughts here. I was inspired by [Ramda.js](https://github.com/ramda/ramda) (as I believe @psliwa also was) and have been working on a similar library for PHP where automatic currying is the main feature: [Phamda](https://github.com/mpajunen/phamda). Currently most of the core functionality is implemented, but for example parameter validation is missing.

Only supporting PHP 5.6 simplifies things a lot. Besides getting rid of all the `call_user_func*`s, variadic functions and argument unpacking can also be really helpful. Automatic currying can still be slow, especially with placeholder arguments and small data sets.

**Comment by lstrojny** [comment]
Closing for now
