### ISSUE TITLE
Is there a roadmap for releasing a 1.0 version?

### ISSUE THREAD

**Issue by matteosister** [lstrojny/functional-php#48]
A stable 1.0 version is on the way anytime soon? 

Many thanks in advance. This is an awesome library!

**Comment by lstrojny** [comment]
@matteosister generally, I do not plan to change significant APIs before 1.0, the package has been quite stable for a long time now and I am happy with most of the design choices. There are a couple of ideas I have, one of them being to remove the C extension as it doesn’t add that much value, esp. for PHP 5.6 where we can get rid of `call_user_func()` and the like. I would generally be interested in what my userbase thinks about the following questions:

 - How important is the C extension to you? Do you use it in production?
 - What PHP version are you on?
 - What do you wish to see in functional PHP?

**Comment by matteosister** [comment]
- I do not use the php extension. It's a pretty large codebase in Symfony2, and we are bringing as many functional approach as possible, but we don't have a pure sysadmin in the team, and composer is a no-brain solution for us.

- we are on php 5.5, because we are using aws elastic beanstalk to deploy our app. We are evaluating a migration to ebs + docker, so we can upgrade immediatly to 5.6. It's a matter of weeks anyway.

- This library works great for us. For me there is only one thing that I'd like to see. And it's not really important. I'd like to see an alias for **reduce_** to **fold_**. But as I said who cares? It's just that I love haskell...
A stable release would be great. I like to keep my minimum-stability in "stable". And IMO this library deserves a 1.0.0 release! :+1:

**Comment by egils** [comment]
* I, personally, on my projects do not use the C extension just because I do not have a need for it. It seems to be working fine on small to medium size projects without any noticeable difference.
* Use both PHP 5.5 and 5.6 now but will migrate all project's server base to PHP 5.6 rather soon.
* So far Functional PHP fit my needs.

**Comment by colinodell** [comment]
* I don't use the C extension and don't plan on doing so.  The PHP library is as fast as a non-functional approach would be, and that's good enough for me.
* I've used this library on 5.3, 5.4, and 5.5.
* A stable release :)

**Comment by msadouni** [comment]
- I don't use the C extension
- I use it on 5.3 for now, migration on 5.6 is planned
- A sort function would be nice, like Ruby [Array.sort](http://ruby-doc.org/core-2.2.2/Array.html#method-i-sort). For now I use `usort` but it modifies the collection.

**Comment by lstrojny** [comment]
@msadouni interesting idea to add an F\sort() function. Thank you

**Comment by arvidj** [comment]
Hi, is there anything blocking the release of an alpha? I would love the use some of the features that aren't in the latest release, but cannot since my build software forces me to use tagged releases.

**Comment by lstrojny** [comment]
1.0.0-alpha5 is released

**Comment by matteosister** [comment]
:+1:

**Comment by arvidj** [comment]
thanks a billion!

**Comment by jacobsantos** [comment]
I plan on migrating existing functional style code over to this library as standardization process. I would have just rewrote a lot of the functions, which doesn't make any sense. I don't plan on using the PHP extension in the future and will be using composer.

If there aren't any sort functions, then I might do a pull request when I need to do collections or I guess monoids.

**Comment by lstrojny** [comment]
So, here is the plan: release a 1.0 as far as possible and start working on the following changes for 1.2:

 - Use variadics and callables and bump version requirement to 5.6
 - Use generators for sequences
 - Add partial application function

**Comment by lstrojny** [comment]
1.0.0 has landed, 1.2 has been merged in to master
