### ISSUE TITLE
Tag latest 5.3 release

### ISSUE THREAD

**Issue by LukeMauldin** [lstrojny/functional-php#66]
Please tag the latest 5.3 release.  I am attempting to target the release with composer using ``` "lstrojny/functional-php": "dev-master#a91a38bf25a0dbe41a29b23321ad56647389a4ca",``` but I am still getting an error because it is reading the metadata from the master branch: https://getcomposer.org/doc/04-schema.md#package-links

**Comment by lstrojny** [comment]
Closing.
