### ISSUE TITLE
Possibility of C Extension in future releases

### ISSUE THREAD

**Issue by mfdj** [lstrojny/functional-php#70]
Some background. I found out about this library via the [Functional Programming in PHP](http://www.functionalphp.com/) book, which is a great read. The author recommends this library and rightly so — it looks really great! I'm excited to start using this more in my work. 

I'm opening this issue because I was a little confused. The _Functional Programming in PHP_ author recommended using this library via the C-extension but when I came to this repo I couldn't find the C-source. Then I saw the [PECL](http://pecl.php.net/package/functional) link in the repo's description, which is clearly out of date and was quite confused if I even had the correct lib. It took a little digging to find the [Removing C extension](https://github.com/lstrojny/functional-php/commit/8c8d51c92ce3c235bbaf49402b45cdfb27b2d6c8) commit and the [1.0 Roadmap](https://github.com/lstrojny/functional-php/issues/48) issue which illuminate the deprecation of the C-extension.

I'm opening this issue partly to suggest updating the readme to highlight the deprecation but also curious if you'd consider implementing the C-extension at some point in the future? I was curious to test out the performance difference between the C-extension and the pure-PHP implementations but it seems like the difference was maybe negligible?

In situations where I have the option I'd tend to prefer using a C-extension if it I knew it had measurable performance benefits, but I suspect that maintaining both code-bases in tandem is more headache than help.

**Comment by jacobsantos** [comment]
* PHP7 will remove any advantage a C extension may have.
 * I don't think the difference between the two would be that great. The optimizations you could get from C don't really work. There is some gains, obviously, but I believe it is more in the range of micro-optimizations for PHP5. PHP7 will have even less advantage.
 * Other extensions that existed to "optimize" PHP userland code ended up with the same results.

That is to say that to see an advantage, you would want to do some optimizations not in PHP currently, like tail call optimizations, if possible, which might involve hacking the PHP engine. Given also that most of the time will probably

**Comment by lstrojny** [comment]
@mfdj what @jacobsantos said already: the performance differences weren’t that huge (or even not existing) and developing and maintaining it was pretty costly, so I decided to get rid of the burden and go with plain PHP. I added a note to the review though to save the next users some trouble.
Thank you for the report!

**Comment by mfdj** [comment]
Thanks for discussing @lstrojny and @jacobsantos! What you said makes sense.

One last thought, it might be nice to move the PECL link out of the repositories description, and over to your deprecation message:

![screen shot 2015-09-13 at 10 53 35 am](https://cloud.githubusercontent.com/assets/1110910/9837968/c3958d14-5a05-11e5-94f8-3bcebef05f1b.png)
