### ISSUE TITLE
First and last should throw an error if the collection is empty.

### ISSUE THREAD

**Issue by hoesler** [lstrojny/functional-php#81]
I my opinion ```fist``` and ```last``` should throw sth like a ```NoSuchElementException``` if the collection is empty instead of returning ```null```. This would avoid the ambiguity with ```null``` as a value.
Further, I would prefer removing the callable argument and introduce a ```find``` function for that purpose.

P.S.: Great library. Thanks!

**Comment by ahungry** [comment]
In most lisps, returning an element from an empty collection results in 'nil' (which is like false and null combined in lisp, but closest to null in php).

I disagree with throwing an error in such cases, although perhaps a magic number constant would be better (some hex value like a null byte defined as a constant that equates to NIL perhaps? `define('NIL', '0x00')` or some such)

Then if someone wants to treat it as a false-y value, they can (int) cast the 0x00 to a basic 0 (false in php)

**Comment by lstrojny** [comment]
@hoesler I have given this some thought and I will not break BC on this. If this is an important use case to you, feel free to open a PR adding a `first_or_throw`/`last_or_throw`.
