### ISSUE TITLE
More efficient autoloading?

### ISSUE THREAD

**Issue by adamelso** [lstrojny/functional-php#84]
This is a great library, but unfortunately we may end up having to uninstall it because installing it with Composer has added a huge difference to the page load, as profiled with BlackFire.

(Sadly autoloading functions won't be added to PHP [anytime soon](http://blog.ircmaxell.com/2013/09/rambling-on-internals.html)).

One solution I thought of it adding generation of the functions to Symfony's `bootstrap.php.cache` file.

However I'm wondering if this library would benefit from providing its own solution for optimizing the loading of functions?

<img width="1679" alt="screen shot 2016-03-31 at 11 59 28" src="https://cloud.githubusercontent.com/assets/5972864/14173816/475733e4-f738-11e5-8e4f-e4174e8a7cb7.png">
<img width="1677" alt="screen shot 2016-03-31 at 11 59 54" src="https://cloud.githubusercontent.com/assets/5972864/14173815/47549eea-f738-11e5-9580-d603d173e5e0.png">

**Comment by lstrojny** [comment]
As we no longer support the C extension to be installed side-by-side, would a static require list fix it for you?

**Comment by adamelso** [comment]
@lstrojny Thank you, I'll give it a try and report back :+1:

**Comment by adamelso** [comment]
I believe this new autoloading is performing better, though it's hard to tell; The relative cost of the Composer autoloading path may have decread by could have been skewed by other changes in our codebase.

<img width="1159" alt="screen shot 2016-04-06 at 10 24 22" src="https://cloud.githubusercontent.com/assets/5972864/14312030/4e4e65f6-fbe2-11e5-80c1-7e9eae0b37d9.png">
<img width="1464" alt="screen shot 2016-04-06 at 10 27 23" src="https://cloud.githubusercontent.com/assets/5972864/14312031/4e4e96ac-fbe2-11e5-86cd-0328bca8b582.png">

**Comment by lstrojny** [comment]
Alright, the new method should indeed work better. Closing this for now, OK?

**Comment by adamelso** [comment]
@lstrojny All good, thank you :+1:
