### ISSUE TITLE
the removed C extension

### ISSUE THREAD

**Issue by c9s** [lstrojny/functional-php#87]
Hi,

I am pretty interested in that extension, would you mind moving the extension into a separated repository?

**Comment by lstrojny** [comment]
@c9s I am happy for anyone to take it over but I will not maintain it myself anymore. Feel free to pick it up, here is the last revision: 48f934bbc7f412813d01388c27599cc32edca78a

**Comment by c9s** [comment]
Thanks!

Lars Strojny <notifications@github.com> 於 2016年5月9日 星期一寫道：
