### ISSUE TITLE
Documentation is hard to use

### ISSUE THREAD

**Issue by cuongthamhl** [lstrojny/functional-php#88]
I used to be able to search the usage of functions easily since they were all on the same page. After the docs have bee divided into multiple pages, I find it's rather inconvenient when finding usage for a specify function. 

I propose that this repo should revert back to the old way of organization for documentations.

**Comment by lstrojny** [comment]
Understood and sorry it pains you. Would you mind filing a pull request unifying the docs but keeping a table of contents?

**Comment by ahungry** [comment]
You should rewrite the docs into an emacs org-mode file (it allows export to texinfo, man format, and html/pdf, and markdown - gives you a TOC for free too).

Maybe I'll set this up for you sometime

**Comment by soutoner** [comment]
I have an unified version of the docs with a doctoc-generated TOC. I you want I can make a pull request.

**Comment by lstrojny** [comment]
Sounds good, go ahead!
