### ISSUE TITLE
HHVM usage broken

### ISSUE THREAD

**Issue by shadowhand** [lstrojny/functional-php#97]
Started getting this error on our Travis builds, first seen today:

```
Fatal error: Parameter $functions is variadic and has a type constraint (callable); variadic params with type constraints are not supported in /home/travis/build/equip/assist/vendor/lstrojny/functional-php/src/Functional/Compose.php on line 54
```

Full build is here https://travis-ci.org/equip/assist/jobs/141634731

**Comment by shadowhand** [comment]
cc @ameech @elazar @dolfelt

**Comment by elazar** [comment]
Potentially related: facebook/hhvm#4858 and facebook/hhvm#6954

**Comment by dantleech** [comment]
Just to note this works on the 1.2.0 branch but not on 1.2.1.

**Comment by elazar** [comment]
Looks like b09b096ecc15758991fa3d99488b036d8fcf60f6 was the offending commit.

**Comment by elazar** [comment]
From what I can gather, the check for use of typehints with variadic functions is determined at compile time by HHVM. As such, the runtime check currently present in `src/Functional/Compose.php` has no effect.
